name: CZITools

channels:
  - conda-forge
      
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - pillow
  - joblib
  - pip
  - pip:
    - pylibCZIrw
    - aicspylibczi>=3.1.1
    - fsspec>=2022.8.0