name: CZITools

channels:
  - conda-forge

dependencies:
  # conda_core
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - joblib
  - pip
  # conda_spec
  - pillow
  - spyder
  - pip:
    # pip_core
    # pip_spec
    - pylibczirw
    - aicspylibczi>=3.1.1
    - fsspec>=2022.8.0